trigger:
    - feature/checkout
pool:
  name: 'Hosted VS2017'
  demands:
  - msbuild
  - visualstudio

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  inputs:
     command: 'restore'
     restoreSolution: '**/*.sln'
     feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
     command: 'build'
     projects: |
       **/*.sln

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'D:\a\1\s\src\SwedbankPay.Sdk.Tests\SwedbankPay.Sdk.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:\a\1\s\src\Sample.AspNetCore.SystemTests'
    ArtifactName: 'SystemTests'
    publishLocation: 'Container'



