pool:
  name: 'Hosted VS2017'
  demands:
  - msbuild
  - visualstudio

variables:
  imageName: 'payex.client.ci:$(build.buildId)'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/*.sln
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: |
#      **/SwedbankPay.Sdk/*.csproj
#      **/Sample.AspNetCore/*.csproj

#- task: NuGetCommand@2
#  inputs:
#    command: 'pack'
#    packagesToPack: 'src/SwedbankPay.Sdk/SwedbankPay.Sdk.csproj'
#    versioningScheme: 'off'

# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



