# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  name: 'Hosted VS2017'
  demands:
  - msbuild
  - visualstudio

variables:
  imageName: 'payex.client.ci:$(build.buildId)'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'SwedbankPay/swedbank-pay-sdk-dotnet/src/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/*.sln

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: |
#      **/SwedbankPay.Sdk/*.csproj
#      **/Sample.AspNetCore/*.csproj

#- task: NuGetCommand@2
#  inputs:
#    command: 'pack'
#    packagesToPack: 'src/SwedbankPay.Sdk/SwedbankPay.Sdk.csproj'
#    versioningScheme: 'off'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
