trigger:
    - feature/checkout
pool:
  name: 'Hosted VS2017'
  demands:
  - msbuild
  - visualstudio

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.

      $ApiBaseUrl = "$(SwedbankPayConnectionSettings.ApiBaseUrl)"
      [System.Environment]::SetEnvironmentVariable("SwedbankPayConnectionSettings.ApiBaseUrl", $ApiBaseUrl, "User")

      $Token = "$(SwedbankPayConnectionSettings.Token)"
      [System.Environment]::SetEnvironmentVariable("SwedbankPayConnectionSettings.Token", $Token, "User")

      $TermsOfServiceUrl = "$(Urls.TermsOfServiceUrl)"
      [System.Environment]::SetEnvironmentVariable("Urls.TermsOfServiceUrl", $TermsOfServiceUrl, "User")

      $CancelUrl = "$(Urls.CancelUrl)"
      [System.Environment]::SetEnvironmentVariable("Urls.CancelUrl", $CancelUrl, "User")

      $CompleteUrl = "$(Urls.CompleteUrl)"
      [System.Environment]::SetEnvironmentVariable("Urls.CompleteUrl", $CompleteUrl, "User")

      $HostUrls = "$(Urls.HostUrls)"
      [System.Environment]::SetEnvironmentVariable("Urls.HostUrls", $HostUrls, "User")

       Write-Host ([System.Environment]::GetEnvironmentVariable("SwedbankPayConnectionSettings.ApiBaseUrl", "User"))
       Write-Host ([System.Environment]::GetEnvironmentVariable("SwedbankPayConnectionSettings.Token", "User"))
       Write-Host ([System.Environment]::GetEnvironmentVariable("Urls.TermsOfServiceUrl", "User"))
       Write-Host ([System.Environment]::GetEnvironmentVariable("Urls.CancelUrl", "User"))
       Write-Host ([System.Environment]::GetEnvironmentVariable("Urls.CompleteUrl", "User"))
       Write-Host ([System.Environment]::GetEnvironmentVariable("Urls.HostUrls", "User"))
      
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  inputs:
     command: 'restore'
     restoreSolution: '**/*.sln'
     feedsToUse: 'select'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/*.sln
    arguments: '--configuration $(BuildConfiguration)'    
  


- task: MSBuild@1
  displayName: 'Build system tests project'
  inputs:
    solution: '**\Sample.AspNetCore.SystemTests.csproj'
    platform: AnyCPU
    configuration: Release
  enabled: false

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'D:\a\1\s\src\SwedbankPay.Sdk.Tests\SwedbankPay.Sdk.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src\Sample.AspNetCore.SystemTests'
    ArtifactName: 'SystemTests'
    publishLocation: 'Container'



