# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'payex.client.ci:$(build.buildId)'

steps:
- script: docker build -f Linux.Dockerfile -t $(imageName) .
  displayName: 'docker build'


- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src\Sample.AspNetCore3/Sample.AspNetCore3.csproj'
    feedsToUse: 'config'
    nugetConfigPath: '**/nuget.config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src\Sample.AspNetCore3/Sample.AspNetCore3.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src\Sample.AspNetCore3/Sample.AspNetCore3.csproj'
    versioningScheme: 'off'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'