# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

jobs:

- job: build

  pool:
      name: Hosted VS2017

  steps:
    - script: echo Payex Sample build 
      displayName: 'Build Intro'


    - task: UseDotNet@2
      displayName: 'Install .net core 3.0 (preview)'
      inputs:
        packageType: sdk
        version: 3.0.x
        includePreviewVersions: true
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'src\Sample.AspNetCore3\Sample.AspNetCore3.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Sample.AspNetCore3/Sample.AspNetCore3.csproj'

    - task: NuGetCommand@2
      inputs:
        command: 'pack'
        packagesToPack: 'src\Sample.AspNetCore3\Sample.AspNetCore3.csproj'
        versioningScheme: 'off'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'