trigger:
    - feature/checkout
pool:
  name: 'Hosted VS2017'
  demands:
  - msbuild
  - visualstudio

steps:

#- task: NuGetCommand@2
#  inputs:
#    command: 'restore'
#    restoreSolution: '**/*.SystemTests/packages.config'
#    feedsToUse: 'select'
#    restoreDirectory: '..\packages'
#- task: MSBuild@1
#  inputs:
#    solution: '**/*.SystemTests.csproj'
#    platform: '$(BuildPlatform)'
#    configuration: '$(BuildConfiguration)'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'

- task: NuGetCommand@2
  inputs:
     command: 'restore'
     restoreSolution: '**/*.sln'
     feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
     command: 'build'
     projects: |
       **/*.sln

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\SwedbankPay.Sdk.Tests\*test*.dll
      !**\SwedbankPay.Sdk.Tests\*TestAdapter.dll
      !**\SwedbankPay.Sdk.Tests\**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

# #- task: DotNetCoreCLI@2
# #  inputs:
# #    command: 'build'
# #    projects: |
# #      **/SwedbankPay.Sdk/*.csproj
# #      **/Sample.AspNetCore/*.csproj

# #- task: NuGetCommand@2
# #  inputs:
# #    command: 'pack'
# #    packagesToPack: 'src/SwedbankPay.Sdk/SwedbankPay.Sdk.csproj'
# #    versioningScheme: 'off'

# # Copy files
# # Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)

# #- task: DotNetCoreCLI@2
# #  inputs:
# #    command: 'test'
# #    projects: '**/SwedbankPay.Sdk/*.csproj''/SwedbankPay.Sdk.csproj'
# #- task: VSTest@2
# #  inputs:
# #    testSelector: 'testAssemblies'
# #    testAssemblyVer2: |
# #      **\*test*.dll
# #      !**\*TestAdapter.dll
# #      !**\obj\**
# #    searchFolder: '$(System.DefaultWorkingDirectory)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'publish'
#    publishWebProjects: true
#    zipAfterPublish: true
#    arguments: '--output $(Build.ArtifactStagingDirectory)'

#- task: PublishBuildArtifacts@1
#  inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      cd "D:\a\1\s\src"
#      ls

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: 'D:\a\1\s\src\Sample.AspNetCore.SystemTests'
#    ArtifactName: 'SystemTests'
#    publishLocation: 'Container'



