# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'payex.client.ci:$(build.buildId)'

steps:
- script: docker build -f Linux.Dockerfile -t $(imageName) .
  displayName: 'docker build'


- task: CopyFiles@2
  displayName: 'Copy generated content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/artifacts'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/outpout
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
    publishLocation: 'Container'


