# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'macOS-latest'

steps:
- task: NuGetToolInstaller@1
  #inputs:
    #versionSpec: '5.3.1'

- task: NuGetCommand@2
  displayName: 'Restoring packages'
  inputs:
     command: 'restore'
     restoreSolution: '$(Build.SourcesDirectory)\src\SwedbankPay.Sdk.sln'
     feedsToUse: 'select'

- task: UseDotNet@2
  displayName: 'Setting up framework for build'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Build solution for .net core projects'
  inputs:
    command: 'build'
    projects: |
      **/SwedbankPay.Sdk.csproj
      **/Sample.AspNetCore.csproj
    arguments: '--configuration $(BuildConfiguration)'
