name: "Build site, test, and publish"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore ./src/SwedbankPay.Sdk.sln

    - name: Build SDK
      run: dotnet build --configuration Release --no-restore src/SwedbankPay.Sdk/SwedbankPay.Sdk.csproj

    - name: Build SDK Tests
      run: dotnet build --configuration Release --no-restore src/SwedbankPay.Sdk.Tests/SwedbankPay.Sdk.Tests.csproj

    - name: Run SDK Tests
      run: dotnet test --configuration Release src/SwedbankPay.Sdk.Tests/SwedbankPay.Sdk.Tests.csproj
      env:
        SwedbankPayConnectionSettings__Token: ${{ secrets.MERCHANT_TOKEN }}
    
    - name: Build SDK Sample project
      run: dotnet build --configuration Release --no-restore src/Samples/Sample.AspNetCore/Sample.AspNetCore.csproj

    - name: Build SDK Sample test project
      run: dotnet build --configuration Release --no-restore src/Samples/Sample.AspNetCore.SystemTests/Sample.AspNetCore.SystemTests.csproj

    - name: Run SDK Sample prject tests
      run: dotnet test --configuration Release src/Samples/Sample.AspNetCore.SystemTests/Sample.AspNetCore.SystemTests.csproj
      env:
        SwedbankPayConnectionSettings__Token: ${{ secrets.MERCHANT_TOKEN }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3

      with:
          versionSpec: '5.3.x'


    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.3

      
    - name: Publish to NuGet
      uses: rohith/publish-nuget@v2.5.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src\SwedbankPay.Sdk\SwedbankPay.Sdk.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: SwedbankPay.Sdk:${{ steps.gitversion.outputs.nuGetVersionV2 }}
        TAG_COMMIT: false
        NUGET_KEY: ${{ secrets.NUGET_KEY}}
